export const GET_CLIENT_LIST_LOADING = 'GET_CLIENT_LIST_LOADING';
export const GET_CLIENT_LIST_SUCCESS = 'GET_CLIENT_LIST_SUCCESS';
export const GET_CLIENT_LIST_FAILED = 'GET_CLIENT_LIST_FAILED';

export const GET_CURRENT_CLIENT = 'GET_CURRENT_CLIENT';

export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';